### ISSUE TITLE
Look at Mek machine  the client will be severely stuck  and   the numeric value shows the overflow

### ISSUE THREAD

**Issue by FortyTwoCn** [DrManganese/TOPAddons#118]
https://github.com/McJtyMods/TheOneProbe/issues/656

**Describe the bug**
Look at Mek machine  the client will be severely stuck  and   the numeric value shows the overflow

**To Reproduce**
Look at Mek machine 

**Expected behavior**
The value is displayed normally, and the client is not stuck

**Screenshots**
![image](https://github.com/user-attachments/assets/edb2f04d-f60c-49ac-9ede-16c24fd2b6ba)
![image](https://github.com/user-attachments/assets/05bb761a-ecc8-4124-bb63-441ffd1392a9)

**Mod environment (please complete the following information):**
 - Forge version: 36.4.21
 - TheOneProbe - 1.16-3.1.7 
 - topaddons-1.16.5-2.2.0-beta
```
**Additional context**
[19十月2024 20:49:19.428] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (1214906 > 131068)
at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:336) ~[?:?]
at net.minecraft.network.PacketBuffer.func_192575_l(PacketBuffer.java:366) ~[?:?]
at net.minecraftforge.common.extensions.IForgePacketBuffer.readRegistryId(IForgePacketBuffer.java:98) ~[forge:?]
at mekanism.api.chemical.gas.GasStack.readFromPacket(GasStack.java:79) ~[mekanism:10.1.2]
at mekanism.api.chemical.ChemicalUtils.readGasStack(ChemicalUtils.java:49) ~[mekanism:10.1.2]
at mekanism.common.integration.lookingat.theoneprobe.TOPChemicalElement$GasElement.(TOPChemicalElement.java:33) ~[mekanism:10.1.2]
at mcjty.theoneprobe.apiimpl.ProbeInfo.createElements(ProbeInfo.java:28) ~[theoneprobe:1.16-3.1.7]
at mcjty.theoneprobe.apiimpl.ProbeInfo.fromBytes(ProbeInfo.java:15) ~[theoneprobe:1.16-3.1.7]
at mcjty.theoneprobe.network.PacketReturnInfo.(PacketReturnInfo.java:25) ~[theoneprobe:1.16-3.1.7]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:106) ~[forge:?]
at java.util.Optional.map(Optional.java:215) ~[?:?]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:106) ~[forge:?]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge:?]
at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[forge:?]
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[forge:?]
at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[forge:?]
at java.util.Optional.map(Optional.java:215) ~[?:?]
at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[forge:?]
at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1905) ~[?:?]
at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
at net.minecraft.client.main.Main.main(Main.java:184) ~[量子科技.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.41.jar:36.2]
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?]
at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]


```

**Comment by DrManganese** [comment]
Looking at the stack trace you provided, the network error seems to be coming from Mekanism's integration: `mekanism.common.integration.lookingat.theoneprobe.TOPChemicalElement$GasElement`.

I would not expect to see TOPAddons' fluid gauge on that block as Mekanism provides its own TOP integration. By default, the fluid gauge is supposed to be disabled for their blocks.
Could you check whether in topaddons' common config, the option 'gaugeModBlacklist' still contains "mekanism", and "mekanismgenerators"?

**Comment by FortyTwoCn** [comment]
[forge]
	#List of mod IDs for which no TOP Addons fluid gauge should be shown
	gaugeModBlacklist = ["mekanism", "mekanismgenerators", "fluidtank"]

[storagedrawers]
	#Hide info when drawer is concealed
	hideConcealed = false

Yes  and The probability of this happening is not very high
