### ISSUE TITLE
[Bug] Error executing task

### ISSUE THREAD

**Issue by MysticAura** [DrManganese/TOPAddons#14]
MC: 1.10.2
Forge: 2121
Mod Version: topaddons-1.10.2-0.9.0

Issue: Not much to say other than NPE error that requires attention.

[NPE Log](http://pastebin.com/5Shux6se)

**Comment by DrManganese** [comment]
Thanks for the report, could you tell me what actions to take to reproduce this error?

**Comment by MysticAura** [comment]
I'm not entirely sure. Bug testing a pack and found the error when log searching for things to iron out. I'll let you know when I'm able to trigger it again.

**Comment by DrManganese** [comment]
Alright, just as an fyi, this piece of code normally triggers when a player joins a world.

**Comment by KasperFranz** [comment]
This is also happening on my server,(running HermitPack with Sponge) not sure what is causing it.

**Comment by KasperFranz** [comment]
Latest.log

> [12:55:35] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:386) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) ~[PacketUtil.class:1.10.2-2171-5.1.0-BETA-2000]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) ~[fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

there is nothing in the FML log

**Comment by DrManganese** [comment]
@KasperFranz this seems to be a bug related to the right-clicking of an item, it doesn't even mention topaddons. Mystic's error is related to joining a server or typing a command.
This error could still be caused by my mod but I'll need more to go on. :/

**Comment by KasperFranz** [comment]
That is the wrong paste sorry :)  gonna add the right one as soon as I am home again

**Comment by KasperFranz** [comment]
updated my previous post to contain the logs

**Comment by Cobra1117** [comment]
I'm also seeing this error. Using the Spectre Key from the Random Things mod is the easiest way I've found to reproduce the bug.
