### ISSUE TITLE
server stall when entering the nether(topaddons-1.10.2-0.9.0)

### ISSUE THREAD

**Issue by SDUBZ** [DrManganese/TOPAddons#15]
[06:21:31] [Server thread/INFO]: swh65458 joined the game[06:26:58] [Server thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.NullPointerExceptionat java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: java.lang.NullPointerExceptionat io.github.drmanganese.topaddons.config.network.MessageClientOptions.lambda$onMessage$7(MessageClientOptions.java:55) ~[MessageClientOptions.class:?]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]... 5 more[06:26:58] [Server thread/WARN]: Keeping entity chickens.ChickensChicken that already exists with UUID aef4697b-c743-4a2e-84da-864468f1f44f[06:27:03] [Server thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.NullPointerExceptionat java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: java.lang.NullPointerExceptionat io.github.drmanganese.topaddons.config.network.MessageClientOptions.lambda$onMessage$7(MessageClientOptions.java:55) ~[MessageClientOptions.class:?]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]... 5 more[06:27:10] [Server thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.NullPointerExceptionat java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: java.lang.NullPointerExceptionat io.github.drmanganese.topaddons.config.network.MessageClientOptions.lambda$onMessage$7(MessageClientOptions.java:55) ~[MessageClientOptions.class:?]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]... 5 more

**Comment by DrManganese** [comment]
Have you tested if this still occurs with 1.10.2-0.9.1?
