### ISSUE TITLE
Crash with IC2Classic

### ISSUE THREAD

**Issue by Speiger** [DrManganese/TOPAddons#20]
I just got a crash report from one of my testers.
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TOP Addons (topaddons)
Caused by: java.lang.NoClassDefFoundError: ic2/core/item/armor/ItemArmorNanoSuit
	at io.github.drmanganese.topaddons.addons.AddonIndustrialCraft2.getSpecialHelmets(AddonIndustrialCraft2.java:58)
	at io.github.drmanganese.topaddons.AddonManager.addHelmets(AddonManager.java:104)
	at io.github.drmanganese.topaddons.AddonManager.preInit(AddonManager.java:57)
	at io.github.drmanganese.topaddons.TOPAddons.preInit(TOPAddons.java:81)
```
Em yeah just dissable your IC2Plugin when IC2Classic is detected, 
since IC2C adds full support on TOP. 

IC2Classics secondary modID: "IC2-Classic-Spmod"

**Comment by DrManganese** [comment]
Thanks for the report.
Does IC2 Classic have the same modid as experimental, or is it an addon?

**Comment by Speiger** [comment]
It has the same modID since its basicly a remaster of the 1.4.7 IC2. Thats why its sharing the ModID so addons actually can support both if they only use the API.

**Comment by DrManganese** [comment]
Alright. I'll add a check to see if the secondary modid you gave me is loaded and skip the IC2Addon if it is.

**Comment by Speiger** [comment]
thanks
