### ISSUE TITLE
Small error in log when looking at Mekanism's Fluid Tanks

### ISSUE THREAD

**Issue by utoc** [DrManganese/TOPAddons#6]
I think this error goes to you since you try to read fluid levels more "smartly" than TOP itself; if not, let me know and I'll send it to @mcjty's repo

We have Mekanism in the pack, we're getting these when looking at Mek items with fluids/gasses:

```
[15:32:44] [Server thread/DEBUG] [theoneprobe/]: The One Probe catched error:
java.lang.NullPointerException
        at net.minecraftforge.fluids.capability.FluidTankProperties.convert(FluidTankProperties.java:34) ~[FluidTankProperties.class:?]
        at mekanism.common.base.FluidHandlerWrapper.getTankProperties(FluidHandlerWrapper.java:24) ~[FluidHandlerWrapper.class:?]
        at io.github.drmanganese.topaddons.addons.AddonForge.addProbeInfo(AddonForge.java:46) ~[AddonForge.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:136) ~[PacketGetInfo.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:29) ~[PacketGetInfo.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:105) ~[PacketGetInfo$Handler.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:98) ~[PacketGetInfo$Handler.class:?]

```
Full log seen here: https://gist.github.com/utoc/ee216ef1040f6ddfe5bcf8607f736597

TOP did have [an update recently](https://github.com/McJty/theoneprobe/tree/1.10) so that may be part of the issue as well.  Not sure but throwing it out there.

I'm running FML 2092, Mekanism 292 (latest), TOP 1.1.1 and TOPAddons 0.6.0

Let me know if I've left out any important information.
`

**Comment by DrManganese** [comment]
Thanks for the report, seems to be caused by me so I'll look into it asap.

**Comment by DrManganese** [comment]
I can't reproduce this on client or server using the same mod and forge versions. Could you give me an example of a block just to make sure I'm looking at the right stuff? Also if the pack is public could I get a link?

**Comment by utoc** [comment]
Sorry for the delays

Mek's Pressurized Reaction Chamber causes the error the first time, then TOP itself gives this error each time after: `[Server thread/DEBUG] [theoneprobe/]: The One Probe catched error:
java.lang.NullPointerException`

No client errors are present in the log but the TOP overlay has a small error: http://i.imgur.com/5saN5hL.png

I can also make this happen with the Quantum Entangloporter and Mechanical Pipes

Pack is available here (it has its own launcher): http://tinyurl.com/hfgwldy

**Comment by DrManganese** [comment]
After days of looking for what I did wrong I figured out that it's actually because of how Mekanism handles a null value for a block side. I'll catch the error myself for now so it doesn't spam.
